build:
  image: node:4.9
  commands:
    - make install
    - make test

publish:
  coverage:
    # Must match parts of the absolute path
    include: drone-sftp/coverage/lcov.info
    when:
      branch: master
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-sftp
    tag: latest
    when:
      branch: master
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-sftp
    tag: develop
    when:
      branch: develop

plugin:
  name: SFTP
  desc: Publish files and artifacts via SFTP
  type: publish
  image: plugins/drone-sftp
  labels:
    - sftp
    - server
