FROM plugins/base:multiarch@sha256:357e38ab917d1689a8315e2522f3aff3b7908edddcc2c91a3249228604f60cb4

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" \
  org.label-schema.name="Drone GitHub Release" \
  org.label-schema.vendor="Drone.IO Community" \
  org.label-schema.schema-version="1.0"

ADD release/linux/arm64/drone-sftp /bin/
ENTRYPOINT [ "/bin/drone-sftp" ]
