# escape=`
FROM plugins/base:windows-1809-amd64@sha256:80947c36426761acddc564c121ac4f93b347649a1b884b96f4ec962dcaf82a87

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone GitHub Release" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

ADD release/windows/amd64/drone-sftp.exe C:/bin/drone-sftp.exe
ENTRYPOINT [ "C:\\bin\\drone-sftp.exe" ]
