# escape=`
FROM plugins/base:windows-ltsc2022-amd64@sha256:78a677c2cc577039e8ae39307eb96731a06faf0377a53b2e497b84c5e172e340

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone GitHub Release" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

ADD release/windows/amd64/drone-sftp.exe C:/bin/drone-sftp.exe
ENTRYPOINT [ "C:\\bin\\drone-sftp.exe" ]
