FROM plugins/base:multiarch@sha256:fcb1b7f64a98e1166c8fe5bc78c28edfcbaa463211ba343818227244edd95b11

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" \
  org.label-schema.name="Drone GitHub Release" \
  org.label-schema.vendor="Drone.IO Community" \
  org.label-schema.schema-version="1.0"

ADD release/linux/amd64/drone-sftp /bin/
ENTRYPOINT [ "/bin/drone-sftp" ]
