# escape=`
FROM plugins/base:windows-1809-amd64@sha256:7d2cb8243bddbc7196221fa4e4fdfb2e18f7fe3d5878f7bbac951a6830b825c7

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone GitHub Release" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

ADD release/windows/amd64/drone-sftp.exe C:/bin/drone-sftp.exe
ENTRYPOINT [ "C:\\bin\\drone-sftp.exe" ]
