FROM plugins/base:multiarch@sha256:e2ce5bb85315a918f6fd7315fc230041d66716978f217ff5f3d761b046c8edff

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" \
  org.label-schema.name="Drone GitHub Release" \
  org.label-schema.vendor="Drone.IO Community" \
  org.label-schema.schema-version="1.0"

ADD release/linux/arm64/drone-sftp /bin/
ENTRYPOINT [ "/bin/drone-sftp" ]
