# escape=`
FROM plugins/base:windows-ltsc2022-amd64@sha256:91f1ff09691a75624c5ecb31a56f8a2ea0f1f3ed83dd7e523db6cc26ce468242

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone GitHub Release" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

ADD release/windows/amd64/drone-sftp.exe C:/bin/drone-sftp.exe
ENTRYPOINT [ "C:\\bin\\drone-sftp.exe" ]
