FROM plugins/base:multiarch@sha256:2f9405d45b85cdc33a243442c8d921c642276bdeb9987bcef92ab82d2464fdbd

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" \
  org.label-schema.name="Drone GitHub Release" \
  org.label-schema.vendor="Drone.IO Community" \
  org.label-schema.schema-version="1.0"

ADD release/linux/arm64/drone-sftp /bin/
ENTRYPOINT [ "/bin/drone-sftp" ]
