FROM plugins/base:multiarch@sha256:d142624a88ef53dc47357cdb80dc5cf5220e780b894ddfb6760c81dc7511e8d3

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" \
  org.label-schema.name="Drone GitHub Release" \
  org.label-schema.vendor="Drone.IO Community" \
  org.label-schema.schema-version="1.0"

ADD release/linux/amd64/drone-sftp /bin/
ENTRYPOINT [ "/bin/drone-sftp" ]
