# escape=`
FROM plugins/base:windows-1809-amd64@sha256:67fe1fddfad15699db9d575e73405fb32eef74813742218b3f1c5bf5ad5144dc

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone GitHub Release" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

ADD release/windows/amd64/drone-sftp.exe C:/bin/drone-sftp.exe
ENTRYPOINT [ "C:\\bin\\drone-sftp.exe" ]
